name: Chart

on:
  push:
    branches:
      - releases/k8s/release-*
    paths:
      - charts/ingress-nginx/Chart.yaml
  
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v4.1.1

      - name: Set up Git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Lint chart
        run: helm lint charts/ingress-nginx

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and push chart to GHCR
        run: |
          helm package charts/ingress-nginx
          CHART_VERSION=$(grep '^version:' charts/ingress-nginx/Chart.yaml | awk '{print $2}')
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push ingress-nginx-${CHART_VERSION}.tgz oci://ghcr.io/${OWNER}/charts
